package io.github.vn7n24fzkq.cpower.content;


/**
 * The enums are from document 'c power external calls communication protocol'
 */
public enum InstantMessageEffect {
    Draw((byte)0x00),
    FromLeft((byte)0x01),
    FromRight((byte)0x02),
    CenterHorizontal((byte)0x03),
    CenterVertical((byte)0x04),
    ShutterVertical((byte)0x05),
    MoveToLeft((byte)0x06),
    MoveToRight((byte)0x07),
    MoveUp((byte)0x08),
    MoveDown((byte)0x09),
    ScrollToLeft((byte)0x0a),
    ScrollToRight((byte)0x0b),
    Flicker((byte)0x0c),
    ContinuousScrollToLeft((byte)0x0d),
    ContinuousScrollToRight((byte)0x0e),
    ShutterHorizontal((byte)0x0f),
    ClockwiseOpenOut((byte)0x10),
    AnticlockwiseOpenOut((byte)0x12),
    Windmill((byte)0x13),
    WindmillAnticlockwise((byte)0x14),
    RectangleForth((byte)0x15),
    RectangleEntad((byte)0x16),
    QuadrangleForth((byte)0x17),
    QuadrangleEndtad((byte)0x18),
    CircleForth((byte)0x19),
    CircleEndtad((byte)0x1a),
    OpenOutFromLeftUpCorner((byte)0x1b),
    OpenOutFromRightUpCorner((byte)0x1c),
    OpenOutFromLeftBottomCorner((byte)0x1d),
    OpenOutFromRightBottomCorner((byte)0x1e),
    BevelOpenOut((byte)0x1f),
    AntiBevelOpenOut((byte)0x20),
    EnterIntoFromLeftUpCorner((byte)0x21),
    EnterIntoFromRightUpCorner((byte)0x22),
    EnterIntoFromLeftBottomCorner((byte)0x23),
    EnterIntoFromRightBottomCorner((byte)0x24),
    BevelEnterInto((byte)0x25),
    AntiBevelEnterInto((byte)0x26),
    HorizontalZebraCrossing((byte)0x27),
    VerticalZebraCrossing((byte)0x28),
    MosaicBig((byte)0x29),
    MosaicSmall((byte)0x2a),
    RadiationUp((byte)0x2b),
    RadiationDownwards((byte)0x2c),
    Amass((byte)0x2d),
    Drop((byte)0x2e),
    CombinationHorizontal((byte)0x2f),
    CombinationVertical((byte)0x30),
    Backout((byte)0x31),
    ScrewingIn((byte)0x32),
    ChessBoardHorizontal((byte)0x33),
    ChessBoardVertical((byte)0x34),
    ContinuousScrollUp((byte)0x35),
    ContinuousScrollDown((byte)0x36),
    Reserved1((byte)0x37),
    Reserved2((byte)0x38),
    GradualBiggerUp((byte)0x39),
    GradualSmallerDown((byte)0x3a),
    Reserved3((byte)0x3b),
    GradualBiggerVertical((byte)0x3c),
    FlickerHorizontal((byte)0x3d),
    FlickerVertical((byte)0x3e),
    Snow((byte)0x3f),
    ScrollDown((byte)0x40),
    ScrollDownLeftToRight((byte)0x41),
    OpenOutFromTopToBottom((byte)0x42),
    SectorExpand((byte)0x43),
    Reserved((byte)0x44),
    ZebraCrossingHorizontal((byte)0x45),
    ZebraCrossingVertical((byte)0x46),
    Random((byte)0xff);

    public final byte value;
    private InstantMessageEffect(byte value){
        this.value = value;
    }
}
